### ISSUE TITLE
가끔 response에 에러메시지가안뜨고 빈 response만뜨는건왜그럴까요?

### ISSUE THREAD

**Issue by JINHYUKJEONG** [kimytsc/covid-rest-vaccine-macro#1]
몇몇 reservation post request는 response가 정상적으로 받아지는데 대부분은 response가 비어있네요.. 그냥 비어있는 수량이올라오면서생기는 카카오 백신 api오류인걸까요?

**Comment by kimytsc** [comment]
> 몇몇 reservation post request는 response가 정상적으로 받아지는데 대부분은 response가 비어있네요.. 그냥 비어있는 수량이올라오면서생기는 카카오 백신 api오류인걸까요?

원인 추정은 네트워크 응답 시간과 해당 시간 전후로의 Network 응답 기록을 봐야알 수 있을 것 같지만, reservation post request의 response가 비어있었다면 높은 확률로 카카오의 트래픽이 높아 응답시간초과가 된 것이 아닐까 생각됩니다.

**Comment by JINHYUKJEONG** [comment]
그냥무시하고돌려도되겠죠? 서울지역같은경우에는 백신뜨자마자 트래픽이 몰리니..

**Comment by kimytsc** [comment]
> 그냥무시하고돌려도되겠죠? 서울지역같은경우에는 백신뜨자마자 트래픽이 몰리니..

네, 무시하셔도 됩니다. 응답시간초과면 이미 실패했을 가능성이 높아서요.

**Comment by JINHYUKJEONG** [comment]
여기서 더개선할사항이안보여서아쉽네요.. 좀더하면 더잘걸릴수있을것같은데..

**Comment by kimytsc** [comment]
> 여기서 더개선할사항이안보여서아쉽네요.. 좀더하면 더잘걸릴수있을것같은데..

API 응답을 기다릴 수밖에 없는 상황이다 보니, 상황이 어쩔 수 없는 것 같습니다.
다만, 네이버 지도 API가 3초면 응답에러가 뜨지만 KAKAO API는 응답 대기시간이 3분으로 체크됩니다. KAKAO도 3초가 지나면 실패한 거로 생각하여 기존 응답을 중단하고 재시도하거나 끝내도록 개선하는 방향이 있을 것 같습니다.

**Comment by JINHYUKJEONG** [comment]
선생님 디스코드 noghye#0128혹은 카카오톡 jinhyeok2020으로 연락부탁드립니다
