### ISSUE TITLE
안녕하세요, 다시 문의드립니다.

### ISSUE THREAD

**Issue by leegajsdoifb** [kimytsc/covid-rest-vaccine-macro#10]
먼저, 귀중한 공유 감사드립니다.
아까까지는 잘 됐었는데
다시 크롬 창에 입력했는데 주소창이 하얗게 변하고 페이지가 안 뜹니다..!

**Comment by kimytsc** [comment]
> 먼저, 귀중한 공유 감사드립니다.
> 아까까지는 잘 됐었는데
> 다시 크롬 창에 입력했는데 주소창이 하얗게 변하고 페이지가 안 뜹니다..!

방금 테스트해보니 잘 되는 것 같은데, 다시 한번 시도해보시겠어요?
