### ISSUE TITLE
안녕하세요 delay, timeout 문의드립니다.

### ISSUE THREAD

**Issue by jiyuha** [kimytsc/covid-rest-vaccine-macro#12]
안녕하세요 :) 
먼저 코드 공유해주심에 감사한 마음 전해드리고 싶습니다!
제가 궁금한 부분은 기본으로 설정되어있는 delay, timeout - 1000, 3000을 수정하여도 실행되는데 큰 지장이 없는지(?) 입니다.
더욱 개선하려면 어떻게 숫자를 수정해야할까요 ..? ㅠㅠ 실행되는 중에 선착순 마감이 수십번 되다보니 속상해서용 ,, >ㅜ<

**Comment by kimytsc** [comment]
> 안녕하세요 :)
> 먼저 코드 공유해주심에 감사한 마음 전해드리고 싶습니다!
> 제가 궁금한 부분은 기본으로 설정되어있는 delay, timeout - 1000, 3000을 수정하여도 실행되는데 큰 지장이 없는지(?) 입니다.
> 더욱 개선하려면 어떻게 숫자를 수정해야할까요 ..? ㅠㅠ 실행되는 중에 선착순 마감이 수십번 되다보니 속상해서용 ,, >ㅜ<

delay는 병원 리스트를 갱신하는 최소 시간이며 timeout은 리스트를 가져올때 timeout 시간보다 오래걸리면 중단하고 다시 가져오는 값입니다. 그래서 delay, timeout 수치를 수정해도 실행되는데는 지장이 없습니다.
다만, delay를 너무 짧게 잡으면 너무 잦은 호출로 인해 일시적으로 IP 차단이 되는 경우가 있으니 감안하여 조정하시면 됩니다.
timeout도 너무 짧으면 병원 리스트를 가져오기 전에 중단시키는 경우가 발생하니 2,000보다는 크게 설정하시는걸 추천드립니다(단, 자체적으로 네이버는 3,000(3초), 카카오는 180,000(3분)의 timeout이 존재).

**Comment by jiyuha** [comment]
감사합니다 !!
