### ISSUE TITLE
안녕하세요 지도 크기에 대해 질문합니다

### ISSUE THREAD

**Issue by liza0627** [kimytsc/covid-rest-vaccine-macro#13]
정보공유 해주셔서 너무 감사합니다.

지도 크기를 설정할때 병원 리스트 크기가 어느정도가 적합한가요? 200대면 무난한가요? 위치 조금 바꾼 창 조금 더 키면 막힐까요?
아니면 한 창에 병원 리스트를 1000까지 나오도록 하는건 괜찮나요?

굳이 고르신다면 어떤게 더 나은가요?

감사합니다

**Comment by kimytsc** [comment]
> 정보공유 해주셔서 너무 감사합니다.
> 
> 지도 크기를 설정할때 병원 리스트 크기가 어느정도가 적합한가요? 200대면 무난한가요? 위치 조금 바꾼 창 조금 더 키면 막힐까요?
> 아니면 한 창에 병원 리스트를 1000까지 나오도록 하는건 괜찮나요?
> 
> 굳이 고르신다면 어떤게 더 나은가요?
> 
> 감사합니다

카카오는 병원 리스트를 가져올때 1000개를 한번에 다 가져오는 것으로 추정됩니다(단, 200개 정도는 확인되었으나 1000개까지는 테스트 안해본 상태). 하지만 네이버는 병원 리스트를 가져올때 무조건 100개씩밖에 못가져오기 때문에, 1000개의 리스트를 확인하려면 10번 호출해야 합니다.

1000개 정도 되려면 범위가 꽤 넓어야 할텐데 주변 200개정도 나오게 하는게 적당하지 않을까 생각됩니다.

**Comment by bien-max** [comment]
안녕하세요 좋은 코드 공유해주셔서 감사합니다. ㅎㅎ
readme를 읽던 중 작은 의문이 생겨 질문드립니다.

choice에서 제가 원하는 백신을 남기면, 남긴 백신에 대해 신청을 하는 것이 맞는지 궁금합니다.

(choice에서 모든 백신을 지우면, 모든 백신에 대해 신청을 한다는 말이 조금 헷갈려 혹시나해서 여쭤봅니다...ㅎㅎ)

**Comment by kimytsc** [comment]
> 안녕하세요 좋은 코드 공유해주셔서 감사합니다. ㅎㅎ
> readme를 읽던 중 작은 의문이 생겨 질문드립니다.
> 
> choice에서 제가 원하는 백신을 남기면, 남긴 백신에 대해 신청을 하는 것이 맞는지 궁금합니다.
> 
> (choice에서 모든 백신을 지우면, 모든 백신에 대해 신청을 한다는 말이 조금 헷갈려 혹시나해서 여쭤봅니다...ㅎㅎ)

화이자만 찾으려면 화이자만 남기고 나머지를 다 지우시면 됩니다. readme도 이해하기 쉽게 다시 수정해두도록 하겠습니다.
