### ISSUE TITLE
too many requests 오류 질문합니다.

### ISSUE THREAD

**Issue by swoo9799** [kimytsc/covid-rest-vaccine-macro#15]
264개 병원에 대해서 매크로를 돌리고 있는데 콘솔창에서 too many 오류가 뜨고있습니다. 
시간은 5초마다 변경되는데 이거는 문제가 없는지 여쭈어봅니다.

**Comment by kimytsc** [comment]
> 264개 병원에 대해서 매크로를 돌리고 있는데 콘솔창에서 too many 오류가 뜨고있습니다.
> 시간은 5초마다 변경되는데 이거는 문제가 없는지 여쭈어봅니다.

429 too many requests가 뜨는건, 너무 잦은 호출로 인한 일시적인 차단으로 보입니다.

그리고 5초마다 시간이 변경되는건, 네이버측에서 전달해주는 갱신된 시간의 텀이 대략 5초정도라 그런 것으로 파악됩니다.

**Comment by HappyHand2** [comment]
delay를 몇 초정도로 하면 too many requests에 안 걸릴까요?
그리고 delay를 너무 올리면 다른 매크로 속도 싸움에 항상 밀릴까요?

**Comment by kimytsc** [comment]
> delay를 몇 초정도로 하면 too many requests에 안 걸릴까요?
too many requests에 안걸리는 시간은 네이버측에서 정해놓은 것이라 저도 알 수 없습니다.

> 그리고 delay를 너무 올리면 다른 매크로 속도 싸움에 항상 밀릴까요?
갱신된 정보를 가장 정확한 타이밍에 가져올 수 없기 때문에 delay를 조정하여 빨라도, 느려도 밀리는건 결국 비슷합니다.
다만, 네이버 API 데이터로 추정하면 새로운 백신수량 갱신에는 5초정도가 걸리는 것으로 추정되니 5000보다 높을 경우에는 밀릴 것으로 생각됩니다.

**Comment by moguv587** [comment]
![image](https://user-images.githubusercontent.com/28014096/128665245-dac55ed2-5cce-4764-978f-14c8ab776b86.png)

A large number of AZ vaccines were released in the Gyeonggi-do area today
The script will request a bunch of hospitals at the same time, causing a 429 error and blocking the account for 1 hour

**Comment by moguv587** [comment]
I just filter AZ because it too much 

.then(res => { 
      while (bussiness = res.shift()) { 
        let hasQuantity = false; 
        business.vaccineQuantity.list.forEach(item => { 
          if (item.quantity > 0 && item.quantityStatus === 'some' && item.vaccineType !== 'AZ') { 
            hasQuantity = true; 
          } 
        }); 
 
        hasQuantity && setTimeout(vaccineMacro.standby, 1, bussiness); 
      } 
    })

**Comment by kimytsc** [comment]
> ![image](https://user-images.githubusercontent.com/28014096/128665245-dac55ed2-5cce-4764-978f-14c8ab776b86.png)
> 
> A large number of AZ vaccines were released in the Gyeonggi-do area today
> The script will request a bunch of hospitals at the same time, causing a 429 error and blocking the account for 1 hour

AZ는 50세 이상만 신청 가능합니다. 그거다보니 수량이 거의 줄어들지 않았고 계속 신청 시도한 것으로 보입니다.
AZ is only available to those 50 years of age or older. As a result, the quantity has hardly decreased, and it seems that they have continued to try to apply.

그래서 네이버측에서 429 too many requests를 응답하지 않았나 생긱됩니다.
So, it seems that Naver did not respond to 429 too many requests.

AZ를 제거하고 업데이트된 버전으로 시도해보시길 바랍니다.
Please remove AZ and try again with an updated version.

**Comment by moguv587** [comment]
Seems filter does not work before, I only set choice to Pfizer this afternoon, but now work, it would still request all hospitals with vaccines, not just Pfizer's, causing the account to be blocked for an hour

I have simply added some code at line 151 to fixed that

```javascript
.then(res => {
      while (bussiness = res.shift()) {
        let hasQuantity = false;
        business.vaccineQuantity.list.forEach(item => {
          if (item.quantity > 0 && item.vaccineType !== 'AZ') {
            hasQuantity = true;
          }
        });

        hasQuantity && setTimeout(vaccineMacro.standby, 1, bussiness);
      }
    })
```

**Comment by kimytsc** [comment]
> Seems filter does not work before, I only set choice to Pfizer this afternoon, but not work, it would still request all hospitals with vaccines, not just Pfizer's, causing the account to be blocked for an hour
> 
> I have simply added some code at line 151 to fixed that
> 
> ```js
> .then(res => {
>       while (bussiness = res.shift()) {
>         let hasQuantity = false;
>         business.vaccineQuantity.list.forEach(item => {
>           if (item.quantity > 0 && item.vaccineType !== 'AZ') {
>             hasQuantity = true;
>           }
>         });
> 
>         hasQuantity && setTimeout(vaccineMacro.standby, 1, bussiness);
>       }
>     })
> ```

알려주신대로 수정하는 과정에서 네이버 백신 필터 로직이 잘못되어있어 수정했습니다. 감사합니다.
In the process of fixing it, the filter process was wrong, so I fixed it. thank you.
