### ISSUE TITLE
failed to fetch 오류

### ISSUE THREAD

**Issue by Frenchkebab** [kimytsc/covid-rest-vaccine-macro#16]
Uncaught (in promise) DOMException: The user aborted a request.

Uncaught (in promise) TypeError: Failed to fetch

위 두 에러가 계속 발생하고 있는데요,
정상적으로 동작하는 것인지요?

화면에서는 계속
잔여백신 접종 신청이 선착순 마감되었습니다.

라고 나오네요

**Comment by kimytsc** [comment]
> Uncaught (in promise) DOMException: The user aborted a request.
> 
> Uncaught (in promise) TypeError: Failed to fetch
> 
> 위 두 에러가 계속 발생하고 있는데요,
> 정상적으로 동작하는 것인지요?
> 
> 화면에서는 계속
> 잔여백신 접종 신청이 선착순 마감되었습니다.

해당 메세지는 API 호출 응답시간이 timeout의 설정된 시간(default 3초)보다 길어져 강제로 중단되었을때 노출되는 메세지입니다.
네이버나 카카오쪽 트래픽이 몰려 응답시간이 늦어지는 경우에 주로 발생하는 것으로 파악됩니다.
