### ISSUE TITLE
속도 관련해 여쭤봅니다

### ISSUE THREAD

**Issue by liza0627** [kimytsc/covid-rest-vaccine-macro#19]
카톡이랑 네이버 중 더 잘 잡히는게 있을까요?
200-300개 병원 리스트를 지역별로 3개의 창을 띄우고 있는데 계속 실패를 해서요ㅠㅠ
네이버로 했을때 한시간 만에 예약했는데 지금 카카오로 하려고 하니까 계속 놓치네요

감사합니다

**Comment by kimytsc** [comment]
> 카톡이랑 네이버 중 더 잘 잡히는게 있을까요?
> 200-300개 병원 리스트를 지역별로 3개의 창을 띄우고 있는데 계속 실패를 해서요ㅠㅠ
> 네이버로 했을때 한시간 만에 예약했는데 지금 카카오로 하려고 하니까 계속 놓치네요
> 
> 감사합니다

체감상 네이버가 확률이 더 높은 것 같은데, 뭐가 더 잘 잡힌다고는 확정지을 수가 없을 것 같습니다.

추가 질문은 [Discussions](https://github.com/kimytsc/covid-rest-vaccine-macro/discussions)를 이용해주세요.
