### ISSUE TITLE
안녕하세요 모바일에서 사용하려고 하면

### ISSUE THREAD

**Issue by d6gkyuj** [kimytsc/covid-rest-vaccine-macro#22]
그냥 메모장에서 수정 후 인증이랑 지도하고..
크롬어플 주소창에 
javascript: 를 포함해서 붙여넣고 기다리면 되나요?

**Comment by kimytsc** [comment]
> 그냥 메모장에서 수정 후 인증이랑 지도하고..
> 크롬어플 주소창에
> javascript: 를 포함해서 붙여넣고 기다리면 되나요?

`javascript:`는 직접 적으시고 Mobile 소스를 복사하여 붙여넣으시면 됩니다. 

주소창에 javascript: 로 시작하는 소스를 복붙하면 javascript:가 없어진 상태로 주소창에 붙히기 떄문입니다.
ex) javascript:alert("테스트"); 를 복사해서 붙여넣으면 alert("테스트");만 주소창에 붙여넣어짐

추가질문은 [Discussions](https://github.com/kimytsc/covid-rest-vaccine-macro/discussions)를 이용해주세요.
