### ISSUE TITLE
안녕하세요 macro 시도해보는 중에 에러가 생겨서요ㅠ

### ISSUE THREAD

**Issue by baksuski** [kimytsc/covid-rest-vaccine-macro#4]
VM276:95 Uncaught TypeError: Cannot read property 'html' of null
    at Object.mounted (<anonymous>:95:18)
    at <anonymous>:339:14
라는 에러가 뜨는데 혹시 해결방법 도와주실 수 있으세요?ㅠㅠ

$('.h_title').html(`<span class="accent"><span id="organizations">0</span>개 리스트에서 잔여백신</span> 예약시도중`);

이 부분인 것 같아요!
올려주신것만으로도 너무 감사합니다ㅠㅠㅠ

**Comment by kimytsc** [comment]
> VM276:95 Uncaught TypeError: Cannot read property 'html' of null
> at Object.mounted (:95:18)
> at :339:14
> 라는 에러가 뜨는데 혹시 해결방법 도와주실 수 있으세요?ㅠㅠ
> 
> $('.h_title').html(`<span class="accent"><span id="organizations">0</span>개 리스트에서 잔여백신</span> 예약시도중`);
> 
> 이 부분인 것 같아요!
> 올려주신것만으로도 너무 감사합니다ㅠㅠㅠ

스크립트 시도해보실때 접속하신 URL이 `https://v-search.nid.naver.com/reservation/info?key=XXXXX` 와 같이 나와있으신가요?

만약 아니시라면, [예약 신청 페이지 #L6](https://github.com/kimytsc/covid-rest-vaccine-macro/blob/main/naver/macro.js#L6) ~ [예약 신청 페이지 #L10](https://github.com/kimytsc/covid-rest-vaccine-macro/blob/main/naver/macro.js#L10) 접근 방법을 다시 확인해주시면 될 것 같습니다.
