### ISSUE TITLE
안녕하세요, 질문이 있어 여쭤봅니다.

### ISSUE THREAD

**Issue by leegajsdoifb** [kimytsc/covid-rest-vaccine-macro#5]
먼저 공유해주셔서 감사합니다.

써주신대로 코드를 입력하니까

0개 리스트에서 잔여백신 예약시도중
라고 뜨는데 왜 개수가 안 뜨는지를 모르겠네요ㅠ

**Comment by jituolee** [comment]
저도 그렇습니다
너무너무 감사합니다 ㅜㅜ
지도 주소 지대로 넣어도
0개의 리스트 중에서  라고 뜹니다

**Comment by kimytsc** [comment]
0개 리스트가 뜬다는건
1. 리스트를 못가져오거나(이미 너무 많은 횟수로 인해 ip가 잠시 차단된 경우)
2. 영역이 제대로 설정되지 않았거나
3. 해당 영역에 병원이 없거나
중에 해당될 것 같습니다.

1번 상황은... delay를 1000이나 2000정도 맞춰서 늦게 호출하여 되도록 차단 안당하는 방법 말고는 어떻게 할 수가 없습니다...

2번 상황의 경우, 스크립트를 실행하면 하단에 `예약시도 위치 확인`에 지도 이미지가 표시되도록 해놓아서 해당 이미지를 보시고 제대로 된 것인지 확인해주시면 될 것 같습니다.

**Comment by kimytsc** [comment]
스크립트 상에 설정하신 지도 URL을 올려주시면 리스트 정상인지 확인해드릴께요.

**Comment by jituolee** [comment]
선생님
https://m.place.naver.com/rest/vaccine?vaccineFilter=used&x=127.4793555&y=36.6261014&bounds=127.4584558%3B36.6002315%3B127.5002553%3B36.6519626
이 주소인데ㅡ한 번 봐주세요

**Comment by kimytsc** [comment]
> https://m.place.naver.com/rest/vaccine?vaccineFilter=used&x=127.4793555&y=36.6261014&bounds=127.4584558%3B36.6002315%3B127.5002553%3B36.6519626

2021-08-05 19:00:00 기준 64개 리스트 받아오는게 확인되었습니다.

**Comment by jituolee** [comment]
그럼 ip차단확률이 높네요 ㅜㅜ
Ip차단은 방법이 없는거죠?
답변 정말 감사합니다^^

**Comment by kimytsc** [comment]
> 그럼 ip차단확률이 높네요 ㅜㅜ
> Ip차단은 방법이 없는거죠?
> 답변 정말 감사합니다^^

IP차단은 어쩔 수가 없습니다... delay 의 수치를 늘려서 풀렸을때 시도해보시면 됩니다.
