### ISSUE TITLE
{"error":"error occurred"}

### ISSUE THREAD

**Issue by sssfearmot** [kimytsc/covid-rest-vaccine-macro#6]
카카오 계정으로 로그인하고 내 정보 확인을 하는데 계속 {"error":"error occurred"}만 뜹니다...
로그아웃을 하고 다시 해봐도 그러네요 ㅠㅠ

**Comment by kimytsc** [comment]
> 카카오 계정으로 로그인하고 내 정보 확인을 하는데 계속 {"error":"error occurred"}만 뜹니다...
> 로그아웃을 하고 다시 해봐도 그러네요 ㅠㅠ

해당 부분은 쿠키나 로그인 관련 이슈로 보이기는 하는데, 다른 쪽에서도 한번 이슈가 되었던 것 같지만 제가 아직 모르겠네요..

크롬 시크릿모드로 띄워서 로그인 해보시는걸 추천드립니다.
