### ISSUE TITLE
안녕하세요, 에러 관련 질문드립니다

### ISSUE THREAD

**Issue by jewoos9562** [kimytsc/covid-rest-vaccine-macro#7]
안녕하세요, 카카오로 진행 시
### 'Failed to load resource: the server responded with a status of 403 () '
그리고 ### Uncaught (in promise) DOMException: The user aborted a request.
와 같은 에러가 콘솔창에 발생합니다.
혹시 해당 에러가 신청을 했는데 실패해서 발생하는 정상적인 상태인지, 혹은 다른 원인으로 인한 오류인지 여쭤봅니다.

코드 감사드립니다.

**Comment by kimytsc** [comment]
카카오는 잔여백신 예약 시도 실패시 403 응답을 주도록 되어 있는 것 같습니다.
하지만 403이더라도 응답값이 정상적이었다면 화면상에 병원명과 실패 사유(ex, 잔여백신 접종 신청이 선착순 마감되었습니다.)가 노출됩니다.
노출되지 않는다면 에러로 생각되고, 노출된다면 정상입니다.
