### ISSUE TITLE
안녕하세요 리스트가 0개로 뜨는데 이것도 정상 작동 되고 있는건가요?

### ISSUE THREAD

**Issue by dugu21** [kimytsc/covid-rest-vaccine-macro#8]
모바일pc버전으로 주소창에 입력하니깐 0개 리스트에서 잔여백신 예약시도중 이라고 나오는데 

이 경우에도 잔여백신이 뜨면 자동으로 진행되는걸까요?

작성자님 스크린샷을 보고 리스트가 많이 나오는 걸로 되있어서 문의드려봅니다.

**Comment by kimytsc** [comment]
> 모바일pc버전으로 주소창에 입력하니깐 0개 리스트에서 잔여백신 예약시도중 이라고 나오는데
> 
> 이 경우에도 잔여백신이 뜨면 자동으로 진행되는걸까요?
> 
> 작성자님 스크린샷을 보고 리스트가 많이 나오는 걸로 되있어서 문의드려봅니다.

5번 이슈와 동일한 것 같은데, 지도 영역이 잘못 되었거나 과도한 호출로 인한 IP 차단으로 리스트를 못가져오는 것으로 추정됩니다.

**Comment by kimytsc** [comment]
스크립트 상에 설정하신 지도 URL을 올려주시면 리스트가 정상적으로 가져와지는지 확인해드리겠습니다.

**Comment by dugu21** [comment]
pc에선 안되고 핸드폰으로 하니깐 잘 작동되네요 감사합니다.

**Comment by kimytsc** [comment]
동일한 소스라면, PC에서도 동작하는게 정상인데, 여전히 PC에서는 리스트가 0이라면 일시적으로 IP가 차단되었을 가능성이 높겠네요.

**Comment by kimytsc** [comment]
> pc에선 안되고 핸드폰으로 하니깐 잘 작동되네요 감사합니다.

동일한 소스가 PC에서만 안되었다면, IP가 일시적으로 차단되었
