### ISSUE TITLE
네이버에서 막은걸까요? 현재 작동이 안되고있네요.

### ISSUE THREAD

**Issue by WAY2GOOD4U** [kimytsc/covid-rest-vaccine-macro#88]
https://m.place.naver.com/rest/vaccine?vaccineFilter=used로 들어가면 아예 로딩이 안되네요.

https://m.place.naver.com/rest/vaccine?vaccineFilter=used&x=126.9015361&y=37.4858157&bounds=126.8770000%3B37.4560000%3B126.9260000%3B37.5170000로 들어가면 로딩이 되긴하지만 어떠한 병원도 뜨질않습니다. 위치를 서울 중심가로 옮겨도 마찬가지입니다.

병원만 안뜨나싶어서 원하는 지역으로 지도 이동후 현위치로 링크 새로받아 작동시켜봤으나 0개 리스트에서 예약시도중이라고만 뜨네요.

**Comment by WAY2GOOD4U** [comment]
일시적인 점검이었나봅니다 현시간 작동 잘 됩니다

**Comment by kimytsc** [comment]
확인해보니 기존에 안내중이던 URL의 `vaccineFilter=used` 에 의해서 필터가 제대로 먹히지 않아 리스트는 잘 가져왔지만, 지도에서 노출을 못시키고 있어 수정하였습니다.

**Comment by WAY2GOOD4U** [comment]
> 확인해보니 기존에 안내중이던 URL의 `vaccineFilter=used` 에 의해서 필터가 제대로 먹히지 않아 리스트는 잘 가져왔지만, 지도에서 노출을 못시키고 있어 수정하였습니다.

아침에는 단순 서버문제였던거 같습니다. 수정하시기 전 코드로도 예약이 성공적으로 되는게 확인됬습니다.

**Comment by WAY2GOOD4U** [comment]
> > 확인해보니 기존에 안내중이던 URL의 `vaccineFilter=used` 에 의해서 필터가 제대로 먹히지 않아 리스트는 잘 가져왔지만, 지도에서 노출을 못시키고 있어 수정하였습니다.
> 
> 아침에는 단순 서버문제였던거 같습니다. 수정하시기 전 코드로도 예약이 성공적으로 되는게 확인됬습니다.

16시 기준 카카오맵의 전국 모든 병원이 "마감"으로 변경되었고 네이버 지도 또한 "업데이트 지연중" 이라고 표시되는걸 보아 아마도 매크로 방지를 위해서 점검에 들어간게 아닌가 생각됩니다.
