### ISSUE TITLE
감사합니다. 백신선택에 궁금한 점이 있는데 여쭤봐도 될까요

### ISSUE THREAD

**Issue by 33townhouse** [kimytsc/covid-rest-vaccine-macro#9]
부모님 도와드리다가 도저히 불가능해서 검색하다가 들어왔습니다. 스크립트 올려주셔서 감사합니다.

   choice: [
        "VEN00013",/*화이자*/
        "VEN00014",/*모더나*/
        "VEN00015",/*아스트라제네카*/
        "VEN00016",/*얀센*/
    ]
> 특정 백신만을 예약하고 싶다면, 복사한 소스의 choice에서 선택하여 제거합니다.

백신 선택에서 화이자를 맞고싶다면

   choice: [
     
        "VEN00014",/*모더나*/
        "VEN00015",/*아스트라제네카*/
        "VEN00016",/*얀센*/
    ]

이렇게 화이자만 지우면 되는건가요?

**Comment by kimytsc** [comment]
> 부모님 도와드리다가 도저히 불가능해서 검색하다가 들어왔습니다. 스크립트 올려주셔서 감사합니다.
> 
> choice: [
> "VEN00013",/_화이자_/
> "VEN00014",/_모더나_/
> "VEN00015",/_아스트라제네카_/
> "VEN00016",/_얀센_/
> ]
> 
> > 특정 백신만을 예약하고 싶다면, 복사한 소스의 choice에서 선택하여 제거합니다.
> 
> 백신 선택에서 화이자를 맞고싶다면
> 
> choice: [
> 
> ```
>     "VEN00014",/*모더나*/
>     "VEN00015",/*아스트라제네카*/
>     "VEN00016",/*얀센*/
> ]
> ```
> 
> 이렇게 화이자만 지우면 되는건가요?

반대로 화이자를 남기고 나머지를 지우시면 됩니다.

**Comment by 33townhouse** [comment]
답변 정말 감사드립니다.
