### ISSUE TITLE
예약 성공 후 멈추지 않음

### ISSUE THREAD

**Issue by ghost** [kimytsc/covid-rest-vaccine-macro#92]
실제로는 예약이 성공했으나
[병원명] 예약실패가 나오면서 
잔여수량이 사라질때까지 계속해서 예약을 시도합니다.

**Comment by kimytsc** [comment]
네이버 예약 완료 프로세스에서 "SUCCESS"만 있었는데, "SUCCESS_2"가 추가되었음을 확인하였습니다.
해당부분 추가하여 완료로 넘어갈 수 있도록 보완하였습니다.

오류 제보 감사합니다.
